#!/bin/bash

PROGS="zsh vim tmux git backup"

while [ ! -z "$1" ]; do
  case "$1" in
     -i3)
         shift
         PROGS="${PROGS} i3 alacritty wallpaper"
         ;;
     -heaven)
         shift
         PROGS="${PROGS} heaven"
         ;;
     *)
        shift
        echo "Unknown input arg!"
        ;;
  esac
done

echo "Installing ${PROGS}"
stow $PROGS -t $HOME
